### ISSUE TITLE
Container Stops

### ISSUE THREAD

**Issue by jeanpaulrh** [yunussandikci/cloudflare-ddns#1]
Hi, I tried your docker image, and I created it as a stack inside portainer.
It starts, but I receive this error in the logs and the container stops. (domain name and IP redacted)

time="2022-02-02T10:49:20Z" level=info msg="Cloudflare Dynamic DNS Service started."
time="2022-02-02T10:49:20Z" level=info msg="Domains: XXXXXXXX"
time="2022-02-02T10:49:20Z" level=info msg="Interval: 5 minutes"
time="2022-02-02T10:49:21Z" level=info msg="New IP address found: XXXXXXX"
panic: runtime error: index out of range [2] with length 2
goroutine 1 [running]:
github.com/yunussandikci/cloudflare-dnynamic-dns/service.(*updaterService).updateDomains(0xc000110190)
	/app/service/updater_service.go:64 +0x485
github.com/yunussandikci/cloudflare-dnynamic-dns/service.(*updaterService).update(0xc000110190)
	/app/service/updater_service.go:44 +0xca
github.com/yunussandikci/cloudflare-dnynamic-dns/service.(*updaterService).Start(0xc000110190)
	/app/service/updater_service.go:32 +0x2f
main.main()

**Comment by yunussandikci** [comment]
Hello @jeanpaulrh, this issue has been fixed. You can use version 1.0.1 docker image to get a fix. Thanks for letting me know about the issue.
